# ==============================================================================
# EEG Preprocessing Pipeline - Subject Features
# Purpose: Aggregate trial features per subject and compute stability score.
# Input:   data/processed/trial_features.csv  (generated by preprocess_trials.R)
# Output:  data/processed/subject_features.csv
# Usage:   Rscript src/preprocess_subjects.R
# ==============================================================================

library(tidyverse)

input_path  <- "data/processed/trial_features.csv"
output_path <- "data/processed/subject_features.csv"

message("Reading trial features from ", input_path, "...")
all_subjects_features <- read_csv(input_path, show_col_types = FALSE)
message("  -> ", nrow(all_subjects_features), " trials, ",
        n_distinct(all_subjects_features$subject_id), " subjects, ",
        ncol(all_subjects_features), " columns")

# Aggregate per subject: mean and std of each feature across all their trials
message("Aggregating subject-level features (mean + std per feature)...")
feature_cols <- all_subjects_features |>
  select(-subject_id, -trial_id, -run, -label) |>
  colnames()

subject_features <- all_subjects_features |>
  group_by(subject_id) |>
  summarise(
    across(all_of(feature_cols), list(mean = mean, std = sd),
           .names = "{.col}_{.fn}"),
    n_trials = n(),
    .groups = "drop"
  )
message("  -> ", nrow(subject_features), " subjects, ",
        ncol(subject_features), " columns")

# Compute composite stability score per subject.
# Only tsfeature _std columns are used: band power and ERD stds measure
# variability in the task/rest response, not in the intrinsic signal properties,
# so including them would dilute the target definition.
message("Computing stability scores...")
std_cols <- subject_features |>
  select(ends_with("_std")) |>
  select(-contains("_power_"), -contains("_erd_")) |>
  colnames()

# Normalize each std column (z-score) then average across all of them
stability <- subject_features |>
  select(subject_id, all_of(std_cols)) |>
  mutate(across(all_of(std_cols), ~ (. - mean(., na.rm = TRUE)) / sd(., na.rm = TRUE))) |>
  rowwise() |>
  mutate(stability_score = mean(c_across(all_of(std_cols)), na.rm = TRUE)) |>
  ungroup() |>
  select(subject_id, stability_score)

subject_features <- subject_features |> left_join(stability, by = "subject_id")
message("  -> stability_score range: [",
        round(min(stability$stability_score), 3), ", ",
        round(max(stability$stability_score), 3), "]")

message("Saving to ", output_path, "...")
write_csv(subject_features, output_path)
message("Done. ", nrow(subject_features), " subjects, ",
        ncol(subject_features) - 2, " feature columns.")
